### ISSUE TITLE
Draw DAG the same way

### ISSUE THREAD

**Issue by davidchen322** [thieman/dagobah#138]
When the page loads, the DAG should render in the same way every time.  This is especially important when the jobs are complex.

**Comment by thieman** [comment]
The DAG drawing is all handled by [d3.js](http://d3js.org/) using a [force-directed graph](http://bl.ocks.org/mbostock/4062045). This is essentially running a physics emulation to render the nodes in real-time and adapt whenever you add a link or drag things around. It's unlikely we would be able to render the DAG statically without a significant amount of effort, if it is possible at all within the force-directed graph framework.

I'll leave this issue open for a bit to see if anyone else wants to try to work on a PR. I'll close it if there are no takers.

**Comment by thieman** [comment]
Seems unlikely to happen, maybe if D3 even implements this natively we can just flip a switch somewhere.
