### ISSUE TITLE
why the latest dagobah disable the job_on_start action?

### ISSUE THREAD

**Issue by stevenswong** [thieman/dagobah#164]
Hi, thank you for your dagobah. I'am using dagobah for scheduler in pyhton, but the latest version hasn't the job_on_start event, which makes my code written using old dagobah should be changed on new version. So tell me why you do that. Thank you!

**Comment by thieman** [comment]
I can't find any reference to the event you're talking about in the Git history, could you provide an example?

**Comment by stevenswong** [comment]
ohh, it is my fault! I am very sorry, this event was added by myself six months ago, but forgot it.
