### ISSUE TITLE
Changing code to use py-dag as a package instead of the internal file

### ISSUE THREAD

**Issue by cmishra** [thieman/dagobah#180]
There's more advanced functionality in the py-dag package (all_downstreams, for example). This way further improvements to py-dag are automatically incorporated as well. 

I can help with this too. Just wanted to get your thoughts before starting.

**Comment by thieman** [comment]
We are requiring py-dag version 1.0.0 currently. I think the library is currently on 2.5.0.

My general philosophy would be not to upgrade unless there is a feature in the newer version we specifically need, did you have a use case in mind?

**Comment by cmishra** [comment]
I was actually referring to your frozen py-dag version (1.0.0) vs a 'dag.py' file within dagobah itself. 

I realized quickly after submitting that though that the latest dagobah version does already rely on your py-dag repository (instead of the dag.py file). This isn't the same as the version available via `pip install dagobah`. Installing from source left #175, but I haven't run into any problems running dagobah and py-dag 1.0.0 functionality is now available.
