### ISSUE TITLE
Address jump

### ISSUE THREAD

**Issue by douglasren** [thieman/dagobah#191]
When I open the login page, the address will jump to http://www6.getkickstrap.com/?s_token=1533908568.0535445857&searchbox=1&showDomain=1&tdfs=1

**Comment by mercurychs** [comment]
yes, I also encountered this case.

**Comment by douglasren** [comment]
This problem can be solved by configuring the host:
127.0.0.1   www6.getkickstrap.com getkickstrap.com netdna.getkickstrap.com
@yelangchs

**Comment by ssuazo86** [comment]
@douglasren I'm having the same problem cold you elaborate on your fix.

**Comment by rossee** [comment]
Was able to get this working by using @yelangchs fix, but only seems to work with a Firefox browser (Mac OS v61.0.2).

**Comment by hushaoqing** [comment]
1. find your python site-packages
2. cd /lib/python2.7/site-packages/dagobah/
3. grep -rn 'getkickstrap' ./
4. change "//netdna.getkickstrap.com/1.3/Kickstrap/js/kickstrap.min.js" ---> "//cdn.everything.io/kickstart/3.x/js/kickstart.min.js"
5. run dagobahd

Hope it is usefull !

**Comment by douglasren** [comment]
> @douglasren I'm having the same problem cold you elaborate on your fix.
@ssuazo86 
    1. vim /etc/hosts
2.paste  127.0.0.1 www6.getkickstrap.com getkickstrap.com netdna.getkickstrap.com
3.Clear your browser cache
4.Login again
