### ISSUE TITLE
Dagobah's features compared to chronos or azkaban?

### ISSUE THREAD

**Issue by utsengar** [thieman/dagobah#23]
dagobah is exactly what I was looking for, its much simpler (than chronos or azkaban) but also not similar to them.

So some questions/suggestions:
1. Remote task execution? I believe this can be easily implemented via fabric. What do you think about it?  
2. Logging all the task runs. Right now only the most recent task logs can be seen. Adding logs for all the tasks would be a useful feature (atleast for our usecase).  
3. A fairly easy change will be give an option to disable auth if not needed.  

I am playing around with Dagobag and I am trying to work on 1 and 2 now, not sure about the timeline though :)

**Comment by levonk** [comment]
Just a minor correction, Azkaban can be used for anything, not just Hadoop based Map-Reduce.   It can be used only as a superior cron (dependencies, transparency, partial workflows, etc...) only.   You don't need hadoop at all.
